package baseClasses;

import static java.awt.Dialog.DEFAULT_MODALITY_TYPE;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Corne Lukken
 */
public class PopUpJDialog extends javax.swing.JDialog {

    /**
     * Creates new form PopUpJdDialog
     * @param parent
     * @param modal
     */    
    public PopUpJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Pop-up");
        this.setAlwaysOnTop(true);
        this.setMinimumSize(new Dimension(100, 100));
        this.setSize(popUpDimension);
        this.centerFrame();
    }

    // Default popup dimensions
    private Dimension popUpDimension = new Dimension(400, 300);
    
    // Graphics envrioment used to determine aspects of screen and 3D capabilities.

    /**
     *
     */
        protected GraphicsEnvironment graphics = GraphicsEnvironment.getLocalGraphicsEnvironment();
    
    /**
     * Relocate the JDialog to the center of all monitors.
     */
    protected void centerFrame() {
        this.setLocation(graphics.getCenterPoint().x - (this.getSize().width / 2), graphics.getCenterPoint().y - (this.getSize().height / 2));
    }
    
    /**
     * Halt all other program operation until window is closed.
     */
    protected void haltProgram() {
        this.setVisible(false);
        this.setModalityType(DEFAULT_MODALITY_TYPE);
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
