package screen.help;

import baseClasses.ErrorJDialog;
import baseClasses.SwitchingJPanel;
import main.LuggageControl;

/**
 *
 * @author Corne Lukken
 */
public class Removing extends SwitchingJPanel {
    
    // static variables used to identify tabs
    public static final String REMOVE_ENTRIES = "REMOVE_ENTRIES";
    public static final String REMOVE_LINKS = "REMOVE_LINKS";

    public Removing(LuggageControl luggageControl) {
        super(luggageControl);
        initComponents();
    }
    
    /**
     * Tells the screen to switch to a specific tab
     * Use the jPanel class its static strings to identify the tab.
     * @param tabName string of the tab identifying constants.
     */
    public void selectTab(String tabName) {
        if(tabName.equals(REMOVE_ENTRIES)) {
            linkingTab.setSelectedComponent(panelRemoveEntries);
        }
        else if(tabName.equals(REMOVE_LINKS)) {
            linkingTab.setSelectedComponent(panelRemoveLinks);
        }
        else {
            new ErrorJDialog(this.luggageControl, true, "Error: tab does not exist", (new Throwable()).getStackTrace());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenName = new javax.swing.JLabel();
        linkingTab = new javax.swing.JTabbedPane();
        panelRemoveEntries = new javax.swing.JPanel();
        scrollPaneHelpRemoving = new javax.swing.JScrollPane();
        textPaneRemoving = new javax.swing.JTextPane();
        labelHelpRemovingImage = new javax.swing.JLabel();
        helpRemovingHeader = new javax.swing.JLabel();
        labelHelpRemovingOne = new javax.swing.JLabel();
        labelHelpRemovingOTwo = new javax.swing.JLabel();
        labelHelpRemovingTwo2 = new javax.swing.JLabel();
        labelHelpRemovingThree = new javax.swing.JLabel();
        labelHelpRemovingThree2 = new javax.swing.JLabel();
        labelHelpRemovingFour = new javax.swing.JLabel();
        labelHelpRemovingFive = new javax.swing.JLabel();
        labelHelpRemovingFive2 = new javax.swing.JLabel();
        labelHelpRemovingSix = new javax.swing.JLabel();
        labelHelpRemovingSix2 = new javax.swing.JLabel();
        helpRemovingExample = new javax.swing.JLabel();
        panelRemoveLinks = new javax.swing.JPanel();
        scrollPaneHelpRemoving1 = new javax.swing.JScrollPane();
        textPaneRemoving1 = new javax.swing.JTextPane();
        labelHelpRemovingImage1 = new javax.swing.JLabel();
        helpRemovingHeader2 = new javax.swing.JLabel();
        labelHelpRemovingOne2 = new javax.swing.JLabel();
        labelHelpRemovingOne3 = new javax.swing.JLabel();
        labelHelpRemovingOne4 = new javax.swing.JLabel();
        labelHelpRemovingOne5 = new javax.swing.JLabel();
        labelHelpRemovingOne6 = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();

        setDoubleBuffered(false);
        setPreferredSize(new java.awt.Dimension(800, 400));

        screenName.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        screenName.setText("Help - removing");
        screenName.setPreferredSize(new java.awt.Dimension(1920, 1080));

        textPaneRemoving.setEditable(false);
        textPaneRemoving.setText("Only the administrator can remove database entries. The following entries can be removed: Customers, Flights, Luggage, Users. Removing entries also removes any links or references to other entries for instance: removing a suitcase also removes every reference to users finding or losing this suitcase it will be as if the never lost or found it. Removing entries will effect statistics generated for manager type users.");
        scrollPaneHelpRemoving.setViewportView(textPaneRemoving);

        labelHelpRemovingImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/help.removing.one.png"))); // NOI18N

        helpRemovingHeader.setText("To remove an entry the following steps are to be taken.");

        labelHelpRemovingOne.setText("#1 - Login as an administrive user.");

        labelHelpRemovingOTwo.setText("#2 - Proceed to a delete screen by pressing one of the 3 delete screens");

        labelHelpRemovingTwo2.setText("in the top right corner.");

        labelHelpRemovingThree.setText("#3 - On the delete screen fill in as most of details you know about the");

        labelHelpRemovingThree2.setText("you want to remove.");

        labelHelpRemovingFour.setText("#4 - Press the search button, the details will now be filled in the table.");

        labelHelpRemovingFive.setText("#5 - Mark the checkbox on the right under the remove header");

        labelHelpRemovingFive2.setText("for each of the entries you which to be removed.");

        labelHelpRemovingSix.setText("#6 - Press update, all the marked entries will be removed");

        labelHelpRemovingSix2.setText("and the table will be updated with new information.");

        helpRemovingExample.setText("On the right you will see a example of how a delete screen looks");

        javax.swing.GroupLayout panelRemoveEntriesLayout = new javax.swing.GroupLayout(panelRemoveEntries);
        panelRemoveEntries.setLayout(panelRemoveEntriesLayout);
        panelRemoveEntriesLayout.setHorizontalGroup(
            panelRemoveEntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoveEntriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoveEntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneHelpRemoving, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelRemoveEntriesLayout.createSequentialGroup()
                        .addGroup(panelRemoveEntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(helpRemovingHeader)
                            .addComponent(labelHelpRemovingOne)
                            .addComponent(labelHelpRemovingOTwo)
                            .addComponent(labelHelpRemovingTwo2)
                            .addComponent(labelHelpRemovingThree)
                            .addComponent(labelHelpRemovingThree2)
                            .addComponent(labelHelpRemovingFour)
                            .addComponent(labelHelpRemovingFive)
                            .addComponent(labelHelpRemovingFive2)
                            .addComponent(labelHelpRemovingSix)
                            .addComponent(labelHelpRemovingSix2)
                            .addComponent(helpRemovingExample))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHelpRemovingImage)
                .addGap(796, 796, 796))
        );
        panelRemoveEntriesLayout.setVerticalGroup(
            panelRemoveEntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoveEntriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoveEntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHelpRemovingImage)
                    .addGroup(panelRemoveEntriesLayout.createSequentialGroup()
                        .addComponent(scrollPaneHelpRemoving)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(helpRemovingHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpRemovingOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpRemovingOTwo)
                        .addGap(0, 0, 0)
                        .addComponent(labelHelpRemovingTwo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpRemovingThree)
                        .addGap(0, 0, 0)
                        .addComponent(labelHelpRemovingThree2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpRemovingFour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpRemovingFive)
                        .addGap(0, 0, 0)
                        .addComponent(labelHelpRemovingFive2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpRemovingSix)
                        .addGap(0, 0, 0)
                        .addComponent(labelHelpRemovingSix2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(helpRemovingExample)))
                .addGap(12, 12, 12))
        );

        linkingTab.addTab("remove entries", panelRemoveEntries);

        textPaneRemoving1.setEditable(false);
        textPaneRemoving1.setText("Only the administrator can remove database entries. The following entries can be removed: Customers, Flights, Luggage, Users. Removing entries also removes any links or references to other entries for instance: removing a suitcase also removes every reference to users finding or losing this suitcase it will be as if the never lost or found it. Removing entries will effect statistics generated for manager type users.");
        scrollPaneHelpRemoving1.setViewportView(textPaneRemoving1);

        labelHelpRemovingImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/help.removing.two.png"))); // NOI18N

        helpRemovingHeader2.setText("To remove links take the following steps");

        labelHelpRemovingOne2.setText("#1 - Login as an employee user.");

        labelHelpRemovingOne3.setText("#2 - Open a search screen.");

        labelHelpRemovingOne4.setText("#3 - enter the desired details and acquire ");

        labelHelpRemovingOne5.setText("the results.");

        labelHelpRemovingOne6.setText("#4 - open the details screen with the result.");

        javax.swing.GroupLayout panelRemoveLinksLayout = new javax.swing.GroupLayout(panelRemoveLinks);
        panelRemoveLinks.setLayout(panelRemoveLinksLayout);
        panelRemoveLinksLayout.setHorizontalGroup(
            panelRemoveLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoveLinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoveLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneHelpRemoving1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelRemoveLinksLayout.createSequentialGroup()
                        .addGroup(panelRemoveLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHelpRemovingOne6)
                            .addComponent(helpRemovingHeader2)
                            .addComponent(labelHelpRemovingOne2)
                            .addComponent(labelHelpRemovingOne3)
                            .addComponent(labelHelpRemovingOne4)
                            .addComponent(labelHelpRemovingOne5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHelpRemovingImage1)
                .addGap(30, 30, 30))
        );
        panelRemoveLinksLayout.setVerticalGroup(
            panelRemoveLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRemoveLinksLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelRemoveLinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRemoveLinksLayout.createSequentialGroup()
                        .addComponent(scrollPaneHelpRemoving1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpRemovingHeader2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpRemovingOne2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpRemovingOne3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpRemovingOne4)
                        .addGap(0, 0, 0)
                        .addComponent(labelHelpRemovingOne5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelpRemovingOne6))
                    .addComponent(labelHelpRemovingImage1))
                .addGap(11, 11, 11))
        );

        linkingTab.addTab("remove links", panelRemoveLinks);

        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackbackToPreviousScreen(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linkingTab, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(screenName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(screenName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkingTab, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        linkingTab.getAccessibleContext().setAccessibleName("Linking Luggage");
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackbackToPreviousScreen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackbackToPreviousScreen
        this.userNotAFK();
        luggageControl.switchPreviousPanel();
    }//GEN-LAST:event_buttonBackbackToPreviousScreen


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JLabel helpRemovingExample;
    private javax.swing.JLabel helpRemovingHeader;
    private javax.swing.JLabel helpRemovingHeader2;
    private javax.swing.JLabel labelHelpRemovingFive;
    private javax.swing.JLabel labelHelpRemovingFive2;
    private javax.swing.JLabel labelHelpRemovingFour;
    private javax.swing.JLabel labelHelpRemovingImage;
    private javax.swing.JLabel labelHelpRemovingImage1;
    private javax.swing.JLabel labelHelpRemovingOTwo;
    private javax.swing.JLabel labelHelpRemovingOne;
    private javax.swing.JLabel labelHelpRemovingOne2;
    private javax.swing.JLabel labelHelpRemovingOne3;
    private javax.swing.JLabel labelHelpRemovingOne4;
    private javax.swing.JLabel labelHelpRemovingOne5;
    private javax.swing.JLabel labelHelpRemovingOne6;
    private javax.swing.JLabel labelHelpRemovingSix;
    private javax.swing.JLabel labelHelpRemovingSix2;
    private javax.swing.JLabel labelHelpRemovingThree;
    private javax.swing.JLabel labelHelpRemovingThree2;
    private javax.swing.JLabel labelHelpRemovingTwo2;
    private javax.swing.JTabbedPane linkingTab;
    private javax.swing.JPanel panelRemoveEntries;
    private javax.swing.JPanel panelRemoveLinks;
    private javax.swing.JLabel screenName;
    private javax.swing.JScrollPane scrollPaneHelpRemoving;
    private javax.swing.JScrollPane scrollPaneHelpRemoving1;
    private javax.swing.JTextPane textPaneRemoving;
    private javax.swing.JTextPane textPaneRemoving1;
    // End of variables declaration//GEN-END:variables
}
