-- MySQL Script generated by MySQL Workbench
-- wo 11 nov 2015 13:25:51 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `salt` VARCHAR(16) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flights` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `origin` VARCHAR(45) NULL,
  `destination` VARCHAR(45) NULL,
  `datetime` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luggage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luggage` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `client_flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `client_flights` (
  `flights_id` INT UNSIGNED NOT NULL,
  `clients_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`flights_id`, `clients_id`),
  INDEX `fk_client_flights_clients1_idx` (`clients_id` ASC),
  CONSTRAINT `fk_client_flights_flights`
    FOREIGN KEY (`flights_id`)
    REFERENCES `flights` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_flights_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luggage_flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luggage_flights` (
  `flights_id` INT UNSIGNED NOT NULL,
  `luggage_id` INT UNSIGNED NOT NULL,
  INDEX `fk_luggage_flights_flights1_idx` (`flights_id` ASC),
  INDEX `fk_luggage_flights_luggage1_idx` (`luggage_id` ASC),
  CONSTRAINT `fk_luggage_flights_flights1`
    FOREIGN KEY (`flights_id`)
    REFERENCES `flights` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_luggage_flights_luggage1`
    FOREIGN KEY (`luggage_id`)
    REFERENCES `luggage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `client_luggage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `client_luggage` (
  `clients_id` INT UNSIGNED NOT NULL,
  `luggage_id` INT UNSIGNED NOT NULL,
  INDEX `fk_client_luggage_clients1_idx` (`clients_id` ASC),
  INDEX `fk_client_luggage_luggage1_idx` (`luggage_id` ASC),
  CONSTRAINT `fk_client_luggage_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_luggage_luggage1`
    FOREIGN KEY (`luggage_id`)
    REFERENCES `luggage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `table1` (
  `luggage_lost` INT UNSIGNED NOT NULL,
  `luggage_found` INT UNSIGNED NOT NULL,
  `status` VARCHAR(45) NULL,
  INDEX `fk_table1_luggage1_idx` (`luggage_lost` ASC),
  INDEX `fk_table1_luggage2_idx` (`luggage_found` ASC),
  CONSTRAINT `fk_table1_luggage1`
    FOREIGN KEY (`luggage_lost`)
    REFERENCES `luggage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_luggage2`
    FOREIGN KEY (`luggage_found`)
    REFERENCES `luggage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
